services:
  redis:
    container_name: "redis_for_microservices"
    image: "redis:6.2-alpine"
    ports:
      - 6379:6379

  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: mongodb-db
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_data:/data/db

  publisher:
    container_name: importacoes_publisher
    build:
      context: ./importacoes
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./importacoes:/home/node
      - /home/node/node_modules
    ports:
      - "3000:3000"
    expose:
      - 3000
    environment:
      - PORT=${PORT}
    depends_on:
      - redis
      - mongo
    command: yarn start:dev

  subscriber_microservice:
    container_name: subscriber_microservice
    restart: unless-stopped
    build:
      context: ./lambda-eventos-microservice
      dockerfile: ./Dockerfile
      target: dev
    volumes:
      - ./lambda-eventos-microservice:/home/node
      - /home/node/node_modules
    ports:
      - 8082:8082
    expose:
      - 8082
    environment:
      - PORT=${PORT}
    depends_on:
      - redis
      - mongo
    command: yarn start:dev
